#ifndef ___CLIENTMASTERDEF___
#define ___CLIENTMASTERDEF___

#define CLIENTMASTER_JOB 00
#define CLIENTMASTER_TASK 01
#define CLIENTMASTER_GROUP 02
#define CLIENTMASTER_USER 03
#define CLIENTMASTER_SLAVE 04
#define CLIENTMASTER_ADD 00
#define CLIENTMASTER_DEL 010
#define CLIENTMASTER_SET 020
#define CLIENTMASTER_LST 030
#define CLIENTMASTER_GET 040
#define CLIENTMASTER_INF 050
#define CLIENTMASTER_ADL 060
#define CLIENTMASTER_GEL 070

#define CLIENTMASTER_LOGIN_OK 1
#define CLIENTMASTER_LOGIN_NOTUSER 2
#define CLIENTMASTER_LOGIN_INCORRECTPASS 3
#define CLIENTMASTER_LOGIN_NOTACTION 4


#endif
